### ISSUE TITLE
Links to Getting Started in Guided Tour are not working

### ISSUE THREAD

**Issue by JannisBush** [rviscomi/har.fyi#8]
The links at https://har.fyi/guides/guided-tour/ are pointing to https://har.fyi/guides/guided-tour/getting-started.md which does not exist.
They should point to https://har.fyi/guides/getting-started.md or the file should also be available at `/guided-tour/`.

**Comment by rviscomi** [comment]
Good spot, thanks for flagging this. @max-ostapenko are you able to take a look?
